name: aliwaley
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  frino_icons: ^1.0.1+4
  custom_splash: ^0.0.2
  animated_text_kit: ^4.2.1
  slimy_card: ^1.0.4
  flutter_icons: ^1.1.0
  youtube_player_flutter: ^8.0.0
  http: ^0.13.5
  url_launcher: ^6.1.6
  splashscreen: ^1.2.0
  flutter_spinkit: ^5.1.0
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  social_share: ^2.0.5
  image_picker: ^0.8.6
  firebase_storage: ^10.3.11
  rflutter_alert: ^2.0.4
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  firebase_messaging: ^13.1.0
  fancy_bottom_navigation: ^0.3.2
  overlay_support: ^2.0.1
  expand_widget: ^2.1.0
  flutter_gradient_colors: ^2.1.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/payment/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Sniglet
      fonts:
        - asset: fonts/Sniglet-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento-Regular.ttf

    - family: Merienda
      fonts:
        - asset: fonts/Merienda-Regular.ttf
        - asset: fonts/Merienda-Bold.ttf

    - family: Jaldi
      fonts:
        - asset: fonts/Jaldi-Regular.ttf

    - family: ReemKufi
      fonts:
        - asset: fonts/ReemKufi-Regular.ttf

    - family: ArefRuqaa
      fonts:
        - asset : fonts/ArefRuqaa-Bold.ttf

    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.ttf
        - asset: fonts/Gilroy-Medium.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-SemiBold.ttf